// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2A4GBQvEZzEVr0oMV4lVJ49m8wm9vrCY',
    appId: '1:455814901889:web:6450cc7989a812b4645d80',
    messagingSenderId: '455814901889',
    projectId: 'firebase-register-login-123',
    authDomain: 'fir-register-login-123.firebaseapp.com',
    storageBucket: 'firebase-register-login-123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLcL0dfy9PJFmGIjF3m7oZIOAiXFe9sPA',
    appId: '1:455814901889:android:c4802aeec044149a645d80',
    messagingSenderId: '455814901889',
    projectId: 'firebase-register-login-123',
    storageBucket: 'firebase-register-login-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQeTHRZEuR64lJUAis2vhHlDC-hrenZis',
    appId: '1:455814901889:ios:5ba0342b45de0f66645d80',
    messagingSenderId: '455814901889',
    projectId: 'firebase-register-login-123',
    storageBucket: 'firebase-register-login-123.appspot.com',
    iosClientId: '455814901889-to43av2md4d8hlsf2p7q65m3j6qvkng1.apps.googleusercontent.com',
    iosBundleId: 'com.example.registerAndLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQeTHRZEuR64lJUAis2vhHlDC-hrenZis',
    appId: '1:455814901889:ios:03ac5a08349dadbb645d80',
    messagingSenderId: '455814901889',
    projectId: 'firebase-register-login-123',
    storageBucket: 'firebase-register-login-123.appspot.com',
    iosClientId: '455814901889-3bi24v8nbimdat0cio18cgd5qoef9t95.apps.googleusercontent.com',
    iosBundleId: 'com.example.registerAndLogin.RunnerTests',
  );
}
